"use client";

import { useRef, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { iconFor } from "@/lib/icons";
import { DEFAULT_PROJECT } from "@/lib/config/workspace";
import { cn } from "@/lib/utils";

type Surface = "projects" | "plugins" | "mcp" | "agents" | "capabilities" | "imports" | "settings";

const agents = [
  ["SYNTH Core", "General development partner", "Coding · Research", "Ready"],
  ["SYNTH Forge", "Controlled change proposals", "Review · GitHub", "Ready"],
  ["SYNTH Vision", "Design and image context", "Design · Vision", "Preview"],
  ["SYNTH Architect", "Plan systems and milestones", "Planning · Review", "Ready"],
  ["SYNTH Scout", "Explore code and knowledge", "Research · Search", "Ready"],
  ["SYNTH Sentinel", "Guard risky changes", "Testing · Security", "Ready"],
  ["SYNTH Verify", "Validate builds and diffs", "Testing · Review", "Ready"],
] as const;

const capabilities = [
  ["Coding", "Code completion", "Explain code", "Refactoring"],
  ["Research", "Search workspace", "Documentation", "Summarize context"],
  ["Design", "Design to code", "UI generation", "Figma context"],
  ["Planning", "Project planning", "Break down work", "Create proposals"],
  ["Testing", "Test generation", "Bug detection", "Build verification"],
  ["Review", "Code review", "Diff analysis", "Pull request drafts"],
] as const;

const plugins = [
  ["GitHub", "Repository sync and pull requests", "Repository access", "Connected"],
  ["Figma", "Attach design context to a project", "Design context", "Available"],
  ["Supabase", "Authenticated project data", "Project data", "Connected"],
  ["MCP", "Approved tools through ToolPolicy", "Tool approval", "Available"],
] as const;

export function PlatformSurface({ surface }: { surface: Surface }) {
  const [importMode, setImportMode] = useState<"github" | "upload" | "figma">("github");
  const [githubState, setGithubState] = useState("Not connected");
  const [figmaState, setFigmaState] = useState("Not connected");
  const [files, setFiles] = useState<File[]>([]);
  const [mcpConnected, setMcpConnected] = useState(false);
  const [pluginStates, setPluginStates] = useState<Record<string, boolean>>({ GitHub: true, Supabase: true });
  const [directPush, setDirectPush] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);

  const title = surface === "projects" ? "Project overview" : surface === "imports" ? "Import project" : surface === "mcp" ? "MCP connections" : surface === "plugins" ? "SYNTH plugins" : surface === "agents" ? "SYNTH agents" : surface === "capabilities" ? "AI capabilities" : "Project settings";
  const description = surface === "projects" ? "A compact view of the project SYNTH is currently connected to." : surface === "imports" ? "Bring project context into SYNTH without exposing credentials or claiming unsupported actions." : "Keep project context, tools, and changes explicit and reviewable.";

  return <div className="relative min-h-0 flex-1 overflow-y-auto bg-background"><div className="synth-grid pointer-events-none absolute inset-0 opacity-10" /><div className="relative mx-auto flex w-full max-w-6xl flex-col gap-5 px-4 py-5 sm:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-3 border-b border-border/70 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-synth-cyan">SYNTH platform</p><h1 className="mt-1 font-heading text-2xl font-semibold tracking-tight text-balance">{title}</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div><ProjectMark /></div>{surface === "projects" && <ProjectOverview />}{surface === "imports" && <ImportSurface mode={importMode} setMode={setImportMode} githubState={githubState} setGithubState={setGithubState} figmaState={figmaState} setFigmaState={setFigmaState} files={files} setFiles={setFiles} fileInput={fileInput} />}{surface === "mcp" && <McpSurface connected={mcpConnected} setConnected={setMcpConnected} />}{surface === "plugins" && <PluginSurface states={pluginStates} setStates={setPluginStates} />}{surface === "agents" && <AgentSurface />}{surface === "capabilities" && <CapabilitySurface />}{surface === "settings" && <SettingsSurface directPush={directPush} setDirectPush={setDirectPush} />}</div></div>;
}

function ProjectMark() { const Folder = iconFor("folders"); return <div className="flex items-center gap-2 rounded-xl border border-synth-cyan/25 bg-synth-cyan/5 px-3 py-2"><Folder className="size-4 text-synth-cyan" /><div><p className="text-xs font-semibold">{DEFAULT_PROJECT.name}</p><p className="font-mono text-[9px] text-muted-foreground">{DEFAULT_PROJECT.branch} · {DEFAULT_PROJECT.syncState}</p></div></div>; }

function ProjectOverview() { return <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><Card className="border-synth-cyan/20 bg-card/70"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-base">{DEFAULT_PROJECT.name}</CardTitle><CardDescription className="font-mono text-[10px]">anonymikey/SYNTH</CardDescription></div><Badge className="bg-synth-success/10 text-synth-success">Connected</Badge></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Info label="Branch" value={DEFAULT_PROJECT.branch} /><Info label="Framework" value={DEFAULT_PROJECT.framework} /><Info label="Language" value={DEFAULT_PROJECT.language} /><Info label="Files" value={String(DEFAULT_PROJECT.fileCount)} /><Info label="Last synced" value="Just now" /><Info label="Status" value="Repository ready" /></CardContent></Card><div className="flex flex-col gap-4"><Card><CardHeader><CardTitle className="text-sm">Controlled workflow</CardTitle><CardDescription>Changes move through review before they reach a branch.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{["Proposal", "Review", "Approve", "Create branch", "Pull Request"].map((step, index) => <div key={step} className="flex items-center gap-3 rounded-lg border border-border/70 bg-muted/15 px-3 py-2 text-xs"><span className="font-mono text-[10px] text-synth-violet">0{index + 1}</span><span>{step}</span>{index < 2 && <Badge variant="outline" className="ml-auto text-[9px]">Ready</Badge>}</div>)}</CardContent></Card><Card className="border-synth-violet/20"><CardHeader><CardTitle className="text-sm">Pull Request</CardTitle><CardDescription>Reusable result surface for a future approved change.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2"><Info label="Status" value="Awaiting approval" /><Info label="Branch" value="synth/proposal" /><Info label="Base" value="main" /><Info label="Files changed" value="0" /><Button variant="outline" disabled>Open Pull Request</Button></CardContent></Card></div></div>; }

type ImportMode = "github" | "upload" | "figma";
type ImportSurfaceProps = { mode: ImportMode; setMode: (mode: ImportMode) => void; githubState: string; setGithubState: (value: string) => void; figmaState: string; setFigmaState: (value: string) => void; files: File[]; setFiles: (files: File[]) => void; fileInput: React.RefObject<HTMLInputElement | null> };
type UploadImportProps = { files: File[]; setFiles: (files: File[]) => void; fileInput: React.RefObject<HTMLInputElement | null> };
type ToolCardProps = { name: string; description: string; tools: string[]; status: string; action: React.ReactNode };
type PluginSurfaceProps = { states: Record<string, boolean>; setStates: (states: Record<string, boolean>) => void };

function ImportSurface({ mode, setMode, githubState, setGithubState, figmaState, setFigmaState, files, setFiles, fileInput }: ImportSurfaceProps) { return <div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><Card><CardHeader><CardTitle className="text-sm">Choose source</CardTitle><CardDescription>Each source uses an explicit, reviewable setup.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{[["github", "GitHub", "Connect a repository"], ["upload", "Upload files", "Import a local project"], ["figma", "Figma", "Attach a design"]].map(([id, label, detail]) => <button key={id} type="button" onClick={() => setMode(id as ImportMode)} className={cn("flex items-start gap-3 rounded-xl border p-3 text-left transition-colors", mode === id ? "border-synth-cyan/50 bg-synth-cyan/5" : "border-border hover:bg-muted/30")}><span className="mt-0.5 size-2 rounded-full bg-synth-cyan" /><span><span className="block text-sm font-medium">{label}</span><span className="text-xs text-muted-foreground">{detail}</span></span></button>)}</CardContent></Card><Card>{mode === "github" && <GitHubImport state={githubState} setState={setGithubState} />}{mode === "upload" && <UploadImport files={files} setFiles={setFiles} fileInput={fileInput} />}{mode === "figma" && <FigmaImport state={figmaState} setState={setFigmaState} />}</Card></div>; }

function GitHubImport({ state, setState }: { state: string; setState: (value: string) => void }) { return <><CardHeader><CardTitle className="text-base">Import from GitHub</CardTitle><CardDescription>Inspect first. Import only after the repository context is understood.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><label className="flex flex-col gap-2 text-xs font-medium">Repository URL or owner/repository<Input defaultValue="anonymikey/SYNTH" /></label><label className="flex flex-col gap-2 text-xs font-medium">Branch or ref<Input defaultValue="main" /></label><div className="flex items-center gap-2"><Badge variant="outline">{state}</Badge><span className="text-xs text-muted-foreground">Server-side integration boundary</span></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setState("Configuration required")}>Inspect repository</Button><Button onClick={() => setState("Configuration required")}>Import project</Button></div></CardContent></>; }
function UploadImport({ files, setFiles, fileInput }: UploadImportProps) { const total = files.reduce((sum: number, file: File) => sum + file.size, 0); return <><CardHeader><CardTitle className="text-base">Upload project</CardTitle><CardDescription>Files stay local until you explicitly import them.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><input ref={fileInput} type="file" multiple className="sr-only" onChange={(event) => setFiles(Array.from(event.target.files ?? []))} /><div className="rounded-xl border border-dashed border-synth-cyan/30 bg-synth-cyan/5 p-8 text-center"><p className="text-sm font-medium">Drop files here or choose from your computer</p><p className="mt-1 text-xs text-muted-foreground">Folder selection is supported when the browser allows it.</p><Button className="mt-4" variant="outline" onClick={() => fileInput.current?.click()}>Choose files</Button></div><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{files.length} files selected</span><span>{(total / 1024).toFixed(1)} KB</span></div>{files.length > 0 && <div className="max-h-40 overflow-auto rounded-lg border border-border">{files.map((file: File) => <div key={`${file.name}-${file.size}`} className="flex justify-between border-b border-border/60 px-3 py-2 text-xs last:border-0"><span className="truncate">{file.name}</span><span className="text-muted-foreground">{(file.size / 1024).toFixed(1)} KB</span></div>)}</div>}<Button disabled={!files.length}>Import selected files</Button></CardContent></>; }
function FigmaImport({ state, setState }: { state: string; setState: (value: string) => void }) { return <><CardHeader><CardTitle className="text-base">Import from Figma</CardTitle><CardDescription>Attach design context without claiming code generation.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><label className="flex flex-col gap-2 text-xs font-medium">Figma URL<Input placeholder="https://www.figma.com/file/..." /></label><div className="flex items-center gap-2"><Badge variant="outline">{state}</Badge><span className="text-xs text-muted-foreground">Design inspection boundary</span></div><Button variant="outline" onClick={() => setState("Configuration required")}>Inspect design</Button></CardContent></>; }

function McpSurface({ connected, setConnected }: { connected: boolean; setConnected: (value: boolean) => void }) { return <div className="grid gap-4 lg:grid-cols-2"><ToolCard name="Local Demo MCP" description="Safe example tools registered through the existing approval boundary." tools={["calculator", "workspace_info", "search_demo"]} status={connected ? "Connected" : "Available"} action={<Button variant={connected ? "outline" : "default"} onClick={() => setConnected(!connected)}>{connected ? "Disconnect" : "Connect"}</Button>} /><Card><CardHeader><CardTitle className="text-sm">Permissions</CardTitle><CardDescription>Tools never execute arbitrary URLs or bypass ToolPolicy.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{["Enabled", "Disabled", "Requires approval"].map((item) => <div key={item} className="flex items-center justify-between rounded-lg border border-border/70 px-3 py-2 text-xs"><span>{item}</span><Badge variant="outline">{item === "Requires approval" ? "2 tools" : "Safe"}</Badge></div>)}</CardContent></Card></div>; }
function ToolCard({ name, description, tools, status, action }: ToolCardProps) { return <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-sm">{name}</CardTitle><CardDescription>{description}</CardDescription></div><Badge variant="outline">{status}</Badge></div></CardHeader><CardContent className="flex flex-wrap items-center gap-2"><div className="flex flex-1 flex-wrap gap-2">{tools.map((tool: string) => <Badge key={tool} variant="secondary" className="font-mono text-[9px]">{tool}</Badge>)}</div>{action}</CardContent></Card>; }

function PluginSurface({ states, setStates }: PluginSurfaceProps) { return <div className="grid gap-3 sm:grid-cols-2">{plugins.map(([name, description, permission, status]) => <Card key={name}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-sm">{name}</CardTitle><CardDescription>{description}</CardDescription></div><Badge variant="outline">{status}</Badge></div></CardHeader><CardContent className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">Permission: {permission}</span><Button size="sm" variant="outline" onClick={() => setStates({ ...states, [name]: !states[name] })}>{states[name] ? "Disable" : "Enable"}</Button></CardContent></Card>)}</div>; }
function AgentSurface() { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{agents.map(([name, role, capabilities, status]) => <Card key={name}><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle className="text-sm">{name}</CardTitle><Badge variant="outline" className="text-[9px]">{status}</Badge></div><CardDescription>{role}</CardDescription></CardHeader><CardContent><p className="font-mono text-[10px] text-synth-cyan">{capabilities}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Tool permissions are scoped to approved project context.</p></CardContent></Card>)}</div>; }
function CapabilitySurface() { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{capabilities.map(([category, ...items]) => <Card key={category}><CardHeader><CardTitle className="text-sm">{category}</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{items.map((item) => <div key={item} className="rounded-lg border border-border/70 bg-muted/15 px-3 py-2 text-xs">{item}</div>)}</CardContent></Card>)}</div>; }
function SettingsSurface({ directPush, setDirectPush }: { directPush: boolean; setDirectPush: (value: boolean) => void }) { return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-sm">Repository</CardTitle><CardDescription>Project connection and branch safeguards.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Info label="Repository" value="anonymikey/SYNTH" /><Info label="Default branch" value="main" /><Info label="Connection" value="Authenticated" /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Security</CardTitle><CardDescription>Make high-impact actions explicit.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Setting label="Require approval before changes" description="Recommended for generated edits and tool calls." checked /><Setting label="Allow direct main pushes" description="Advanced and high-risk. Off by default." checked={directPush} onCheckedChange={setDirectPush} /></CardContent></Card></div>; }
function Setting({ label, description, checked, onCheckedChange }: { label: string; description: string; checked: boolean; onCheckedChange?: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onCheckedChange} disabled={!onCheckedChange} aria-label={label} /></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-border/60 pb-2 text-xs last:border-0"><span className="text-muted-foreground">{label}</span><span className="font-medium">{value}</span></div>; }

export type { Surface };
  
