import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Archive,
  ArrowUp,
  Bell,
  Blocks,
  BookOpen,
  Brain,
  Bug,
  Check,
  CheckCircle2,
  ChevronDown,
  CircleHelp,
  Code2,
  Copy,
  FileCode2,
  FileText,
  Files,
  FolderKanban,
  Folders,
  GitBranch,
  GitCompare,
  Globe,
  History,
  Maximize,
  Image,
  ImagePlus,
  Info,
  LayoutDashboard,
  Lightbulb,
  Link2,
  Loader2,
  Map,
  MapIcon,
  MessageCircle,
  MessageCirclePlus,
  MessageSquare,
  Mic,
  MoreHorizontal,
  PanelRight,
  Paperclip,
  Pencil,
  PlugZap,
  Plus,
  RefreshCw,
  Route,
  Search,
  Send,
  Settings2,
  Share2,
  ShieldCheck,
  Sparkles,
  Sun,
  Moon,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Wrench,
  X,
} from "lucide-react";

export const ICONS = {
  activity: Activity,
  archive: Archive,
  arrowUp: ArrowUp,
  bell: Bell,
  blocks: Blocks,
  bookOpen: BookOpen,
  brain: Brain,
  bug: Bug,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  circleHelp: CircleHelp,
  code: Code2,
  copy: Copy,
  fileCode: FileCode2,
  fileText: FileText,
  files: Files,
  folderKanban: FolderKanban,
  folders: Folders,
  gitBranch: GitBranch,
  gitCompare: GitCompare,
  globe: Globe,
  history: History,
  maximize: Maximize,
  image: Image,
  imagePlus: ImagePlus,
  info: Info,
  dashboard: LayoutDashboard,
  lightbulb: Lightbulb,
  link: Link2,
  loader: Loader2,
  map: Map,
  mapIcon: MapIcon,
  messageCircle: MessageCircle,
  messageCirclePlus: MessageCirclePlus,
  messageSquare: MessageSquare,
  mic: Mic,
  more: MoreHorizontal,
  panelRight: PanelRight,
  paperclip: Paperclip,
  pencil: Pencil,
  plug: PlugZap,
  plus: Plus,
  refresh: RefreshCw,
  route: Route,
  search: Search,
  send: Send,
  settings: Settings2,
  share: Share2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  sun: Sun,
  moon: Moon,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  trash: Trash2,
  wrench: Wrench,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

const ICON_ALIASES: Record<string, IconName> = {
  "message-circle-2": "messageCircle",
  "code-2": "code",
  "plug-zap": "plug",
  "file-text": "fileText",
  "book-open": "bookOpen",
  "image-plus": "imagePlus",
  "circle-help": "circleHelp",
};

export function iconFor(name: string): LucideIcon {
  return ICONS[name as IconName] ?? ICONS[ICON_ALIASES[name] ?? "circleHelp"] ?? CircleHelp;
}
