"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type Agent = { id: string; label: string; displayName?: string; division?: string; version?: string; source?: string; enabled: boolean; modelPolicy?: string; capabilities?: string[]; permissions?: Record<string, boolean> };

export default function AdminAgentsPage() {
  const [agents, setAgents] = useState<Agent[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/agents").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setAgents(data.agents); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load agents.")); }, []);
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-12"><p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Admin / Agent Registry</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">SYNTH Agents</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Curated, provider-neutral agent contracts with explicit permissions and bounded handoffs.</p></div><Badge variant="outline">{agents.length} registered</Badge></div>{error && <p className="mt-6 text-sm text-destructive">{error}</p>}<div className="mt-8 grid gap-4 md:grid-cols-2"><Card>{agents.map((agent) => <div key={agent.id} className="border-b p-5 last:border-b-0"><div className="flex items-start justify-between gap-4"><div><CardTitle className="text-base">{agent.displayName ?? agent.label}</CardTitle><CardDescription className="mt-1">{agent.division ?? "specialized"} · {agent.id}</CardDescription></div><Badge variant={agent.enabled ? "secondary" : "outline"}>{agent.enabled ? "enabled" : "disabled"}</Badge></div><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline">{agent.modelPolicy ?? "policy pending"}</Badge><Badge variant="outline">v{agent.version ?? "—"}</Badge><Badge variant="outline">{agent.source ?? "synth-native"}</Badge></div><div className="mt-3 flex flex-wrap gap-2">{(agent.capabilities ?? []).slice(0, 5).map((capability) => <Badge key={capability} variant="outline" className="text-[10px]">{capability}</Badge>)}</div></div>)}</Card><Card><CardHeader><CardTitle className="text-base">Security posture</CardTitle><CardDescription>Permissions are separate from persona and remain read-only by default.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm">{["No agent contains provider-specific model IDs", "Repository writes and shell execution are disabled by default", "Agent handoffs are bounded and approval-aware", "Registry data is exposed only through admin authentication"].map((item) => <p key={item} className="rounded-md border bg-muted/20 p-3 text-muted-foreground">{item}</p>)}</CardContent></Card></div></main>;
}
